
---

### 6. **`ci-cd.yml`** (GitHub Actions Workflow)

This CI/CD pipeline file automates the process of building, testing, and deploying your Dockerized Flask application.

**`ci-cd.yml`**:
```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-flask-app:$GITHUB_SHA .

      - name: Run tests inside Docker container
        run: |
          docker run my-flask-app:$GITHUB_SHA pytest  # Adjust based on your testing framework

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-flask-app:$GITHUB_SHA mydockerhubusername/my-flask-app:$GITHUB_SHA
          docker push mydockerhubusername/my-flask-app:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment happens after the build job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull mydockerhubusername/my-flask-app:$GITHUB_SHA

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.167.98.21 "docker pull mydockerhubusername/my-flask-app:$GITHUB_SHA && docker run -d -p 5000:5000 mydockerhubusername/my-flask-app:$GITHUB_SHA"
